version: '3.8'
services:
  frontend:
    build: ./frontend/flutter
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/smart_nutrition_restaurant
    networks:
      - app-network

  ai_service:
    build: ./ai_service
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
