name: my_flutter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  provider: ^6.1.1
  http: ^0.13.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true


