name: my_flutter_app
environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true


