name: ai_nutrition_restaurant
description: AI营养餐厅应用
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI相关
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4

  # 状态管理
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  provider: ^6.0.5

  # 存储
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 网络
  http: ^1.1.0
  connectivity_plus: ^6.1.4
  dio: ^5.3.3
  retrofit: ^4.0.3
  dio_cache_interceptor: ^3.5.0

  # Firebase - 暂时禁用，待配置后启用
  # firebase_core: ^2.15.1
  # firebase_analytics: ^10.4.5
  # firebase_crashlytics: ^3.3.5
  # firebase_performance: ^0.9.2+5

  # 工具
  intl: ^0.20.2
  url_launcher: ^6.1.14
  logger: ^2.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  uuid: ^4.0.0

  # UI组件
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.8
  
  # 动画系统
  flutter_animate: ^4.3.0
  rive: ^0.13.20
  
  # 图表与可视化
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^29.2.5
  
  # AI集成
  tflite_flutter: ^0.11.0
  
  # 文档
  widgetbook: ^3.0.0-beta.26
  json_annotation: ^4.8.1
  
  # 函数式编程
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # 依赖注入
  injectable: ^2.3.0
  get_it: ^7.7.0
  
  # 路由
  auto_route: ^7.9.2
  
  # 领域驱动设计支持
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.6
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.0
  riverpod_generator: ^2.3.5
  
  # 分析和格式化
  flutter_lints: ^2.0.3
  analyzer: ^5.13.0
  
  # 测试
  mockito: ^5.4.2
  mocktail: ^1.0.1
  golden_toolkit: ^0.15.0
  
  # 资源生成
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  
  # 文档生成
  widgetbook_generator: ^3.2.0
  
  # 代码生成器
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  # generate: true  # 暂时禁用l10n生成
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
