name: ai_nutrition_restaurant
description: AI营养餐厅应用
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI相关
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  # 移除provider，统一使用riverpod

  # 存储
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 网络
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  dio_cache_interceptor: ^3.5.0

  # Firebase - 暂时禁用，待配置后启用
  # firebase_core: ^3.6.0
  # firebase_analytics: ^11.3.3
  # firebase_crashlytics: ^4.1.3
  # firebase_performance: ^0.10.0+8

  # 工具
  intl: ^0.20.0
  url_launcher: ^6.3.0
  logger: ^2.4.0
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  package_info_plus: ^8.1.0
  device_info_plus: ^11.1.0
  uuid: ^4.5.1

  # UI组件
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.15
  
  # 动画系统
  flutter_animate: ^4.5.0
  rive: ^0.13.17
  
  # 图表与可视化
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^29.2.5
  
  # AI集成
  # tflite_flutter: ^0.11.0  # 暂时注释，需要特殊配置
  
  # 文档
  # widgetbook: ^3.9.0  # 暂时注释，最新版有breaking changes
  json_annotation: ^4.9.0
  
  # 函数式编程
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # 依赖注入 - 移除injectable，统一使用riverpod
  # injectable: ^2.5.0
  # get_it: ^8.0.0
  
  # 路由
  auto_route: ^9.2.2
  
  # 领域驱动设计支持
  freezed_annotation: ^2.4.4
  
  # 工具依赖
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  # injectable_generator: ^2.6.2  # 移除，使用riverpod
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  
  # 分析和格式化
  flutter_lints: ^4.0.0
  analyzer: ^6.7.0
  
  # 测试
  mockito: ^5.4.4
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  
  # 资源生成
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  
  # 文档生成
  # widgetbook_generator: ^3.9.0  # 暂时注释
  
  # 代码生成器
  retrofit_generator: ^9.1.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  # generate: true  # 暂时禁用l10n生成
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
