name: ai_nutrition_restaurant
description: AI营养餐厅应用
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI相关
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter_hooks: ^0.20.5

  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  # 移除provider，统一使用riverpod

  # 存储 - 简化为两种方案
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  # hive: ^2.2.3  # 移除，对单人开发过于复杂
  # hive_flutter: ^1.1.0

  # 网络 - 统一使用dio
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  dio_cache_interceptor: ^3.5.0

  # Firebase - 暂时禁用，待配置后启用
  # firebase_core: ^3.6.0
  # firebase_analytics: ^11.3.3
  # firebase_crashlytics: ^4.1.3
  # firebase_performance: ^0.10.0+8

  # 工具
  intl: ^0.20.0
  url_launcher: ^6.3.0
  logger: ^2.4.0
  # sqflite: ^2.4.0  # 移除，简化存储方案
  path_provider: ^2.1.4
  package_info_plus: ^8.1.0
  # device_info_plus: ^11.1.0  # 移除，暂时不需要设备信息
  uuid: ^4.5.1

  # UI组件
  cupertino_icons: ^1.0.8
  # data_table_2: ^2.5.15  # 移除，暂时不需要复杂表格
  qr_flutter: ^4.1.0  # 二维码生成
  shimmer: ^3.0.0  # Shimmer加载效果
  share_plus: ^10.0.3  # 分享功能
  csv: ^6.0.0  # CSV导出
  
  # 数据导出相关
  pdf: ^3.11.1  # PDF生成
  printing: ^5.13.2  # PDF打印和分享
  excel: ^4.0.6  # Excel文件操作
  open_file: ^3.5.7  # 打开文件
  
  # 动画系统 - 简化为一种方案
  flutter_animate: ^4.5.0
  # rive: ^0.13.17  # 移除，对单人开发过于复杂
  
  # 图表与可视化 - 只保留开源的fl_chart
  fl_chart: ^0.69.0
  
  # AI集成
  # tflite_flutter: ^0.11.0  # 暂时注释，需要特殊配置
  
  # 文档
  # widgetbook: ^3.9.0  # 暂时注释，最新版有breaking changes
  json_annotation: ^4.9.0
  
  # 函数式编程 - 简化
  # dartz: ^0.10.1  # 移除，对单人开发过于复杂
  equatable: ^2.0.5
  
  # 依赖注入 - 已移除get_it和injectable，统一使用riverpod
  
  # 路由
  go_router: ^14.2.7
  
  # 领域驱动设计支持
  freezed_annotation: ^2.4.4
  
  # 工具依赖
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  
  # 分析和格式化
  flutter_lints: ^4.0.0
  analyzer: ^6.7.0
  
  # 测试 - 简化测试栈
  mocktail: ^1.0.4
  # mockito: ^5.4.4  # 移除，使用mocktail统一
  # golden_toolkit: ^0.15.0  # 移除，对单人开发过于复杂
  
  # 资源生成
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  
  # 文档生成
  # widgetbook_generator: ^3.9.0  # 暂时注释
  
  # hive_generator: ^2.0.1  # 移除，简化存储

flutter:
  uses-material-design: true
  generate: true  # 启用l10n生成
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
