name: ai_nutrition_restaurant
description: AI营养餐厅应用
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4

  provider: ^6.0.0

  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0

  http: ^1.1.0
  connectivity_plus: ^4.0.2

  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_performance: ^0.9.2+5

  intl: ^0.20.2
  url_launcher: ^6.1.14
  logger: ^2.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3

  cupertino_icons: ^1.0.2
  data_table_2: ^2.6.0
  dio: ^5.8.0+1
  widgetbook: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  widgetbook_generator: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - lib/modules/
