# AI智能营养餐厅系统 - 统一版本配置

# 版本管理策略
version_management:
  strategy: "semantic_versioning"
  upgrade_policy: "minor_auto_patch_manual"
  deprecation_notice_period: "3_months"

# 核心技术栈版本
core_technologies:
  # 前端框架
  frontend:
    flutter:
      version: "3.24.3"
      min_version: "3.24.0"
      channel: "stable"
      upgrade_strategy: "follow_stable"
      
    dart:
      version: "3.5.3"
      min_version: "3.5.0"
      upgrade_strategy: "follow_flutter"
      
  # 后端框架
  backend:
    nestjs:
      version: "10.4.4"
      min_version: "10.4.0"
      upgrade_strategy: "follow_lts"
      
    nodejs:
      version: "20.18.0"
      min_version: "20.18.0"
      lts: true
      upgrade_strategy: "follow_lts"
      
    typescript:
      version: "5.6.3"
      min_version: "5.6.0"
      upgrade_strategy: "minor_auto"

# 数据库版本
databases:
  postgresql:
    version: "15.4"
    min_version: "15.0"
    extensions:
      pgvector:
        version: "0.5.0"
        min_version: "0.4.0"
        
  redis:
    version: "7.0.12"
    min_version: "7.0.0"
    upgrade_strategy: "patch_auto"

# 状态管理和工具库
state_management:
  riverpod:
    version: "3.0.9"
    min_version: "3.0.9"
    migration_status: "completed"
    migration_date: "2025-07-23"
    
  freezed:
    version: "2.5.2"
    min_version: "2.5.0"
    usage: "data_model_generation"
    migration_status: "current"

# ORM和数据库工具
orm_tools:
  typeorm:
    version: "0.3.20"
    min_version: "0.3.20"
    framework_integration: "nestjs"
    features:
      - "entity_relations"
      - "query_builder"
      - "migrations"
      - "connection_pooling"
    
  pg:
    version: "8.11.3"
    min_version: "8.10.0"
    description: "PostgreSQL client for Node.js"
    
  reflect_metadata:
    version: "0.1.13"
    min_version: "0.1.13"
    required_for: "typeorm_decorators"

# UI框架和组件
ui_frameworks:
  material_design:
    version: "3.0"
    flutter_version: "3.19.0+"
    
  cupertino:
    version: "builtin"
    flutter_version: "3.19.0+"

# 网络和API
networking:
  dio:
    version: "5.7.0"
    min_version: "5.7.0"
    
  retrofit:
    version: "4.0.3"
    min_version: "4.0.0"

# 本地存储
local_storage:
  hive:
    version: "2.2.3"
    min_version: "2.2.0"
    
  flutter_secure_storage:
    version: "9.0.0"
    min_version: "9.0.0"

# 开发工具
dev_tools:
  flutter_lints:
    version: "3.0.1"
    min_version: "3.0.0"
    
  build_runner:
    version: "2.4.7"
    min_version: "2.4.0"

# 测试框架
testing:
  flutter_test:
    version: "builtin"
    flutter_version: "3.19.0+"
    
  mockito:
    version: "5.4.2"
    min_version: "5.4.0"
    
  integration_test:
    version: "builtin"
    flutter_version: "3.19.0+"

# AI和机器学习
ai_ml:
  langchain:
    version: "0.3.7"
    min_version: "0.3.0"
    ecosystem: "langchain-community"
    components:
      - "chat_models"
      - "embeddings"
      - "vector_stores"
      - "retrievers"
    
  deepseek_api:
    version: "latest"
    compatibility: "openai_compatible"
    api_endpoint: "https://api.deepseek.com"
    models:
      - "deepseek-chat"
      - "deepseek-coder"
    
  openai:
    version: "4.20.1"
    min_version: "4.15.0"
    usage: "compatibility_layer_for_deepseek"
    
  pgvector_node:
    version: "0.1.8"
    min_version: "0.1.5"
    integration: "typeorm_custom_type"
    vector_dimensions: 1536

# 容器化和部署
deployment:
  docker:
    version: "24.0.0"
    min_version: "20.10.0"
    
  docker_compose:
    version: "2.20.0"
    min_version: "2.15.0"

# 版本兼容性矩阵
compatibility_matrix:
  flutter_dart:
    "3.19.0": "3.2.0"
    "3.16.0": "3.1.0"
    
  nestjs_nodejs:
    "10.0.0": "18.17.0"
    "9.0.0": "16.20.0"
    
  typeorm_postgresql:
    "0.3.17": "15.4"
    "0.3.15": "15.0"
    
  pgvector_postgresql:
    "0.5.0": "15.4"
    "0.4.0": "15.0"
    
  langchain_nodejs:
    "0.0.20": "18.17.0"
    "0.0.15": "18.17.0"

# 升级时间表
upgrade_schedule:
  Q4_2024:
    - "Riverpod 2.6.1 → 3.0.0 (已完成)"
    - "TypeORM 0.3.15 → 0.3.17 (已完成)"
    - "pgvector 0.4.0 → 0.5.0 (已完成)"
    
  Q1_2025:
    - "Flutter 3.19 → 3.22 (when stable)"
    - "NestJS 10.0 → 10.x (patch updates)"
    - "LangChain 0.0.20 → 0.1.x (stable release)"
    
  Q2_2025:
    - "PostgreSQL 15 → 16 (when stable)"
    - "Node.js 18 → 20 LTS"
    - "TypeORM 0.3.x → 0.4.x (major update)"

# 版本锁定策略
version_locking:
  production:
    policy: "exact_versions"
    auto_update: false
    
  staging:
    policy: "compatible_versions"
    auto_update: "patch_only"
    
  development:
    policy: "latest_compatible"
    auto_update: "minor_and_patch"

# 依赖安全检查
security_scanning:
  frequency: "weekly"
  tools:
    - "npm_audit"
    - "flutter_pub_audit"
    - "snyk"
  auto_fix: "patch_only"

# 文档版本标记约定
documentation_versioning:
  format: "semantic_version"
  example: "2.1.0"
  update_trigger: "any_dependency_major_update"
  
# 最后更新信息
last_updated: "2025-07-23"
updated_by: "technical_team"
review_cycle: "monthly"
next_review: "2025-08-23"